In [73]:
import pandas as pd
import matplotlib.pyplot as plt

In [74]:
df1=pd.read_csv('Titanic-Dataset.csv')
df1.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [58]:
df2=df1.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')
df2.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [59]:
inputs=df2.drop('Survived', axis='columns')
target=df2['Survived']
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [60]:
inputs

     Pclass     Sex   Age     Fare
0         3    male  22.0   7.2500
1         1  female  38.0  71.2833
2         3  female  26.0   7.9250
3         1  female  35.0  53.1000
4         3    male  35.0   8.0500
..      ...     ...   ...      ...
886       2    male  27.0  13.0000
887       1  female  19.0  30.0000
888       3  female   NaN  23.4500
889       1    male  26.0  30.0000
890       3    male  32.0   7.7500

[891 rows x 4 columns]

In [61]:
from sklearn.preprocessing import LabelEncoder

In [62]:
le_Pclass = LabelEncoder()
le_Sex=LabelEncoder()
le_Age=LabelEncoder()
le_Fare=LabelEncoder()

In [63]:
inputs['Pclass_n']=le_Pclass.fit_transform(inputs['Pclass'])
inputs['Sex_n']=le_Pclass.fit_transform(inputs['Sex'])
inputs['Age_n']=le_Age.fit_transform(inputs['Age'])
inputs['Fare_n']=le_Fare.fit_transform(inputs['Fare'])
inputs.head()

   Pclass     Sex   Age     Fare  Pclass_n  Sex_n  Age_n  Fare_n
0       3    male  22.0   7.2500         2      1     28      18
1       1  female  38.0  71.2833         0      0     51     207
2       3  female  26.0   7.9250         2      0     34      41
3       1  female  35.0  53.1000         0      0     47     189
4       3    male  35.0   8.0500         2      1     47      43

In [64]:
inputs2=inputs.drop(['Pclass','Sex','Age',"Fare"],axis='columns')
inputs2.head()

   Pclass_n  Sex_n  Age_n  Fare_n
0         2      1     28      18
1         0      0     51     207
2         2      0     34      41
3         0      0     47     189
4         2      1     47      43

In [65]:
from sklearn import tree

In [66]:
model = tree.DecisionTreeClassifier()
model.fit(inputs2,target)

DecisionTreeClassifier()

In [67]:
model.score(inputs2,target)

0.9797979797979798

In [68]:
#For prediction use the following reference
# PClass = 0 means 1st class , 1 means 2nd class & 2 means 3rd class
#Sex = O means female and  1 means male

In [69]:
model.predict([[(2),1,22,7]])

C:\Users\ak735\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [70]:
model.predict([[0,0,38,5]])

C:\Users\ak735\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)